# -*- coding: utf-8 -*-
"""neural network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ygfdMkrlqN0Umx3qHqW1vZ6YGfJjAVYa
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

x = np.linspace(3, 9, 1000)
x

np.random.seed(3)
y = np.sin(x) + np.random.normal(0,0.3,1000)

plt.scatter(x,y)

from sklearn.neural_network import MLPRegressor

model = MLPRegressor((100,20))

xx = x.reshape(-1,1)

model.fit(xx,y)

yp = model.fit(xx,y)

yp = model.predict(xx)

plt.scatter(xx,y)
plt.plot(x,yp,'*r')